/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mini_projrct;

/**
 *
 * @author M C S
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NewOrderB = new javax.swing.JButton();
        lBottom = new javax.swing.JButton();
        StaffButton = new javax.swing.JButton();
        TakeAwayB = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Home");
        setBackground(new java.awt.Color(204, 204, 204));
        setSize(new java.awt.Dimension(1000, 630));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NewOrderB.setBackground(new java.awt.Color(175, 116, 116));
        NewOrderB.setFont(new java.awt.Font("SriLankan", 1, 14)); // NOI18N
        NewOrderB.setForeground(new java.awt.Color(228, 223, 218));
        NewOrderB.setText(" New Order");
        NewOrderB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewOrderBActionPerformed(evt);
            }
        });
        getContentPane().add(NewOrderB, new org.netbeans.lib.awtextra.AbsoluteConstraints(396, 404, 128, 40));

        lBottom.setBackground(new java.awt.Color(175, 116, 116));
        lBottom.setFont(new java.awt.Font("SriLankan", 1, 14)); // NOI18N
        lBottom.setForeground(new java.awt.Color(228, 223, 218));
        lBottom.setText(" Late Order");
        lBottom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lBottomActionPerformed(evt);
            }
        });
        getContentPane().add(lBottom, new org.netbeans.lib.awtextra.AbsoluteConstraints(396, 462, 128, 42));

        StaffButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        StaffButton.setText(" Staff");
        StaffButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StaffButtonActionPerformed(evt);
            }
        });
        getContentPane().add(StaffButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(818, 28, 103, -1));

        TakeAwayB.setBackground(new java.awt.Color(175, 116, 116));
        TakeAwayB.setFont(new java.awt.Font("SriLankan", 1, 14)); // NOI18N
        TakeAwayB.setForeground(new java.awt.Color(228, 223, 218));
        TakeAwayB.setText(" Take Away");
        TakeAwayB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TakeAwayBActionPerformed(evt);
            }
        });
        getContentPane().add(TakeAwayB, new org.netbeans.lib.awtextra.AbsoluteConstraints(396, 347, 128, 39));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NewOrderBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewOrderBActionPerformed
        // TODO add your handling code here:
        new CustomerPage().setVisible(true);
        this.setVisible( false);
    }//GEN-LAST:event_NewOrderBActionPerformed

    private void StaffButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StaffButtonActionPerformed
        // TODO add your handling code here:
        new log_in().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_StaffButtonActionPerformed

    private void lBottomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lBottomActionPerformed
        // TODO add your handling code here:
        new Order().setVisible( true);
        this.setVisible( false);
    }//GEN-LAST:event_lBottomActionPerformed

    private void TakeAwayBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TakeAwayBActionPerformed
        // TODO add your handling code here:
        new TakeAwayOrder().setVisible( true);
        this.setVisible( false);
    }//GEN-LAST:event_TakeAwayBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton NewOrderB;
    private javax.swing.JButton StaffButton;
    private javax.swing.JButton TakeAwayB;
    private javax.swing.JButton lBottom;
    // End of variables declaration//GEN-END:variables
}
